"""
G-Coach Real GECToR Diagnostic Tool
==================================
Standalone diagnostic script for investigating real Windows GECToR ONNX model output
and checking whether . -> .What is generated by the model or conversion code.
"""

import sys
import json
import os
from pathlib import Path

from core.analysis.gector import GectorAnalysisEngine
from core.analysis.harper import HarperAnalysisEngine


TEST_TEXT = "The students were very happy. are you doing today on this super duper nice day?"


def run_diagnostic():
    print("=== ENVIRONMENT ===")
    print(f"Python Version: {sys.version}")
    print(f"Current Working Directory: {os.getcwd()}")

    engine = GectorAnalysisEngine()
    print("\n=== MODEL AVAILABILITY ===")
    print(f"Model Directory: {engine.model_dir}")
    onnx_path = engine.model_dir / "model.onnx"
    tokenizer_json = engine.model_dir / "tokenizer.json"
    config_json = engine.model_dir / "config.json"
    
    print(f"model.onnx exists: {onnx_path.exists()}")
    print(f"tokenizer.json exists: {tokenizer_json.exists()}")
    print(f"config.json exists: {config_json.exists()}")

    is_loaded = engine._load_model()
    print("\n=== GECToR MODE ===")
    if is_loaded and engine._model is not None:
        print("Execution Mode: REAL ONNX MODEL")
    else:
        print("Execution Mode: SIMULATION FALLBACK (Real ONNX model binaries not found)")
        print("\n[NOTE] To run this diagnostic with the real model, ensure the 513MB ONNX model files are placed in models/gector/ on Windows.")

    print("\n=== TEST TEXT ===")
    print(f"Text: {repr(TEST_TEXT)}")
    print(f"Length: {len(TEST_TEXT)}")

    print("\n=== GECToR FINDINGS ===")
    gector_findings = engine.analyze(TEST_TEXT)
    if not gector_findings:
        print("No GECToR findings returned.")
    for f in gector_findings:
        print(f"  - Source: {f.source}")
        print(f"    Category: {f.category}")
        print(f"    Original: {repr(f.original)}")
        print(f"    Replacement: {repr(f.replacement)}")
        print(f"    Start: {f.start}, End: {f.end}")
        print(f"    Slice check TEST_TEXT[start:end]: {repr(TEST_TEXT[f.start:f.end])}")
        print(f"    Message: {f.message}")
        print(f"    Confidence: {f.confidence}")
        print(f"    Severity: {f.severity}")
        print(f"    Auto Fixable: {f.auto_fixable}")
        print(f"    Metadata: {f.metadata}")

    print("\n=== RAW GECToR INFORMATION ===")
    if is_loaded and engine._model is not None and engine._tokenizer is not None:
        try:
            encoding = engine._tokenizer.encode(TEST_TEXT)
            print(f"Tokens: {encoding.tokens}")
            print(f"Token IDs: {encoding.ids}")
            print(f"Offsets: {encoding.offsets}")
            
            import numpy as np
            input_ids_np = np.array([encoding.ids], dtype=np.int64)
            attention_mask_np = np.array([[1] * len(encoding.ids)], dtype=np.int64)
            outputs = engine._model.run(None, {"input_ids": input_ids_np, "attention_mask": attention_mask_np})
            
            logits_d, logits_labels = outputs[0], outputs[1] if len(outputs) > 1 else outputs[0]
            print(f"Logits D shape: {logits_d.shape}, Logits Labels shape: {logits_labels.shape}")
        except Exception as e:
            print(f"Error inspecting raw model outputs: {e}")
    else:
        print("Raw model outputs are not available in simulation fallback mode.")

    print("\n=== HARPER FINDINGS (FOR COMPARISON) ===")
    harper_engine = HarperAnalysisEngine()
    harper_findings = harper_engine.analyze(TEST_TEXT)
    if not harper_findings:
        print("No Harper findings returned.")
    for f in harper_findings:
        print(f"  - Source: {f.source}")
        print(f"    Original: {repr(f.original)}")
        print(f"    Replacement: {repr(f.replacement)}")
        print(f"    Start: {f.start}, End: {f.end}")
        print(f"    Slice check: {repr(TEST_TEXT[f.start:f.end])}")
        print(f"    Message: {f.message}")

    print("\n=== . -> .What INVESTIGATION ===")
    has_dot_what = any(f.original == "." and "What" in f.replacement for f in gector_findings)
    if has_dot_what:
        print("Found finding matching '.' -> '.What' (or similar replacement containing 'What').")
    else:
        print("No finding matching '.' -> '.What' found in GECToR findings.")

    print("\n=== CONCLUSION ===")
    if is_loaded and engine._model is not None:
        if has_dot_what:
            print("A. The raw GECToR model output contains a prediction that inserts/replaces with 'What'.")
        else:
            print("B. The raw GECToR model output does NOT contain 'What'; '.What' is NOT produced by the real model in this run.")
    else:
        print("C. The engine is running in simulation fallback mode (ONNX model absent). Cannot determine real neural model prediction until run on Windows with models/gector present.")


if __name__ == "__main__":
    run_diagnostic()
